import AdminSectionPage from "../../components/AdminSectionPage";
import { assignmentModule } from "../../data/adminModules";

const page = {
  title: "Assignment Reports",
  description: "Generate submission and resource usage reports.",
  actionLabel: "Generate Report",
  filters: ["All Courses", "Report Type", "Date Range"],
  columns: [
    "Report",
    "Scope",
    "Period",
    "Generated By",
    "Generated On",
    "Status",
  ],
  rows: [
    [
      "Assignment Submission Report",
      "All Courses",
      "May 2025",
      "Admin",
      "20 May 2025",
      "Completed",
    ],
    [
      "Material Usage Report",
      "Institute Wide",
      "May 2025",
      "Admin",
      "19 May 2025",
      "Completed",
    ],
    [
      "Pending Review Report",
      "All Teachers",
      "Current",
      "Admin",
      "18 May 2025",
      "Completed",
    ],
  ],
};
export default function AssignmentReports({ profile }) {
  return (
    <AdminSectionPage module={assignmentModule} page={page} profile={profile} />
  );
}
