import AdminSectionPage from "../components/AdminSectionPage";
import { reportModule } from "../data/adminModules";

const page = {
  title: "Recent Reports Generated",
  description: "Generate, view and export institute-wide reports.",
  actionLabel: "Generate Report",
  filters: ["2024-2025", "All Batches", "All Courses", "This Month"],
  columns: ["Report Name", "Type", "Generated By", "Generated On", "Status"],
  rows: [
    [
      "Student Summary Report",
      "Student Report",
      "Admin",
      "20 May 2025 10:30 AM",
      "Completed",
    ],
    [
      "Attendance Summary Report",
      "Attendance Report",
      "Admin",
      "20 May 2025 10:25 AM",
      "Completed",
    ],
    [
      "Fee Collection Report",
      "Fee Report",
      "Admin",
      "20 May 2025 10:20 AM",
      "Completed",
    ],
    [
      "Exam Result Report",
      "Exam Report",
      "Admin",
      "19 May 2025 05:15 PM",
      "Completed",
    ],
  ],
  cards: [
    "Student Overview",
    "Attendance Overview",
    "Fee Overview",
    "Exam Overview",
  ],
};

export default function Reports({ profile }) {
  return (
    <AdminSectionPage module={reportModule} page={page} profile={profile} />
  );
}
