import AdminSectionPage from "../../components/AdminSectionPage";
import { reportModule } from "../../data/adminModules";

const page = {
  title: "Student Reports",
  description: "Generate enrollment, performance and student status reports.",
  actionLabel: "Generate Student Report",
  filters: ["Academic Year", "All Batches", "All Courses"],
  columns: [
    "Report",
    "Scope",
    "Period",
    "Generated By",
    "Generated On",
    "Status",
  ],
  rows: [
    [
      "Student Summary",
      "Institute Wide",
      "May 2025",
      "Admin",
      "20 May 2025",
      "Completed",
    ],
    [
      "Admission Report",
      "All Courses",
      "May 2025",
      "Admin",
      "19 May 2025",
      "Completed",
    ],
    [
      "Student Progress",
      "AIENG-2025-A",
      "Semester 1",
      "Admin",
      "18 May 2025",
      "Completed",
    ],
  ],
};
export default function StudentReports({ profile }) {
  return (
    <AdminSectionPage module={reportModule} page={page} profile={profile} />
  );
}
