/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as AdmissionProcessRouteImport } from './routes/admission-process'
import { Route as ApplyOnlineRouteImport } from './routes/apply-online'
import { Route as CareerRouteImport } from './routes/career'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as EventsNewsRouteImport } from './routes/events-news'
import { Route as FacultyRouteImport } from './routes/faculty'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as PlacementsRouteImport } from './routes/placements'
import { Route as StudentLoginRouteImport } from './routes/student-login'
import { Route as TeacherLoginRouteImport } from './routes/teacher-login'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as VisionMissionRouteImport } from './routes/vision-mission'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
})
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
})
const AdmissionProcessRoute = AdmissionProcessRouteImport.update({
  id: '/admission-process',
  path: '/admission-process',
  getParentRoute: () => rootRouteImport,
})
const ApplyOnlineRoute = ApplyOnlineRouteImport.update({
  id: '/apply-online',
  path: '/apply-online',
  getParentRoute: () => rootRouteImport,
})
const CareerRoute = CareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => rootRouteImport,
})
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
})
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
})
const EventsNewsRoute = EventsNewsRouteImport.update({
  id: '/events-news',
  path: '/events-news',
  getParentRoute: () => rootRouteImport,
})
const FacultyRoute = FacultyRouteImport.update({
  id: '/faculty',
  path: '/faculty',
  getParentRoute: () => rootRouteImport,
})
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
})
const PlacementsRoute = PlacementsRouteImport.update({
  id: '/placements',
  path: '/placements',
  getParentRoute: () => rootRouteImport,
})
const StudentLoginRoute = StudentLoginRouteImport.update({
  id: '/student-login',
  path: '/student-login',
  getParentRoute: () => rootRouteImport,
})
const TeacherLoginRoute = TeacherLoginRouteImport.update({
  id: '/teacher-login',
  path: '/teacher-login',
  getParentRoute: () => rootRouteImport,
})
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
})
const VisionMissionRoute = VisionMissionRouteImport.update({
  id: '/vision-mission',
  path: '/vision-mission',
  getParentRoute: () => rootRouteImport,
})

const rootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  AdmissionProcessRoute: AdmissionProcessRoute,
  ApplyOnlineRoute: ApplyOnlineRoute,
  CareerRoute: CareerRoute,
  ContactUsRoute: ContactUsRoute,
  CoursesRoute: CoursesRoute,
  EventsNewsRoute: EventsNewsRoute,
  FacultyRoute: FacultyRoute,
  GalleryRoute: GalleryRoute,
  PlacementsRoute: PlacementsRoute,
  StudentLoginRoute: StudentLoginRoute,
  TeacherLoginRoute: TeacherLoginRoute,
  TestimonialsRoute: TestimonialsRoute,
  VisionMissionRoute: VisionMissionRoute,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)

import type { getRouter } from './router.jsx'
import type { startInstance } from './start.js'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
